### ISSUE TITLE
Set amplification factor for MIRAI  to zero

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/refdata-risk#5]
Suggest to set amplification factor for MIRAI to 0 instead of 1. 
This way Mirai won't mess up numbers, when calculating DDOS as when summing up it will be 0

**Comment by zelima** [comment]
FIXED

**Comment by aaronkaplan** [comment]
> On 13 Mar 2017, at 06:28, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> Suggest to set amplification factor for MIRAI to 0 instead of 1.

+1
